#====================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#====================================================================
# ENV

app.database.username=postgres
app.database.password=Codec123
app.database.host=113.161.103.134
app.database.port=9000
app.database.db=do_an_1

spring.application.name=QLTSApplication
logging.level.com.codec.system=INFO
spring.profiles.active=@spring.profiles.active@
spring.datasource.hikari.poolName=Hikari
spring.data.jpa.repositories.bootstrap-mode=deferred
spring.jpa.properties.hibernate.jdbc.time_zone=GMT+7
spring.jpa.properties.hibernate.query.fail_on_pagination_over_collection_fetch=true
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.jdbc.batch_size=25
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.implicit-strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
spring.jpa.open-in-view=false
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${app.database.username}
spring.datasource.url=jdbc:postgresql://${app.database.host}:${app.database.port}/${app.database.db}
spring.datasource.password=${app.database.password}
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
spring.jpa.properties.hibernate.order_inserts=true
spring.datasource.hikari.auto-commit=false
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.jpa.properties.hibernate.query.in_clause_parameter_padding=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.task.scheduling.thread-name-prefix=CodecSystemApplication-scheduling-
spring.task.execution.pool.keep-alive=10s
spring.task.execution.pool.queue-capacity=100
spring.task.scheduling.pool.size=2
spring.task.execution.pool.max-size=16
spring.task.execution.thread-name-prefix=CodecSystemApplication-task-
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
application.exception.package=org.,java.,net.,jakarta.,com.,io.,de.,com.codec.system
server.port=8088
application.exception.details=false
springdoc.swagger-ui.operationsSorter=alpha
#springdoc.enable-native-support=true
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

# Metrics
management.endpoint.health.group.custom.include=diskSpace,ping
management.endpoint.health.group.custom.show-components=always
management.endpoint.health.group.custom.show-details=always
management.endpoints.web.exposure.include=*

jhipster.cors.allowed-headers='http://113.161.103.134'
jhipster.cors.allowed-methods= '*'
#jhipster.cors.allowed-headers= '*'
jhipster.cors.exposed-headers= 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
#jhipster.cors.allow-credentials= true
jhipster.cors.max-age= 1800


jwt.auth.converter.resource-id=ssc-connect
jwt.auth.converter.principal-attribute=preferred_username



environment= ${app.kafka.env}
app.base-url=http://localhost:8088

app.codec.maxInMemorySize=50MB
#config memory-size
spring.codec.max-in-memory-size=${app.codec.maxInMemorySize}


jwt.secret=a2V5LWZvci1qc3Qtd2l0aC1oczUxMi1tdXN0LWJlLTY0LWJ5dGVzLWxvbmcjISEhIQ==
# 30 giây = 30000
jwt.expiration=86400000
# 1 ngày
jwt.refresh-expiration=	86400000


